server:
  context-path: /uaa
  port: 5000

management:
  security:
    enabled: false
  port: 5005
  context-path: /mgmt

eureka:
  instance:
    health-check-url-path: /health
    status-page-url-path: /info
    metadata-map:
      management.context-path: /mgmt

spring:
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
