server:
  context-path: /uaa
  port: 5000

management:
  security:
    enabled: false
  context-path: /

eureka:
  instance:
    health-check-url-path: /uaa/mgmt/health
    status-page-url-path: /uaa/mgmt/info
    metadata-map:
      management.context-path: /

spring:
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
